---
- hosts: sickbeard
  vars_files:
    - vars/main.yml
    #- vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  sudo_user: $global_sudo_user
  #roles:
  #  - git-ppa/roles/ppa-dep
  #  - git-ppa
  #  - gitlab-ruby-deps
  #  - ruby-from-src 
  #  - {role: ssl-certs, when: https == 'true'}
  tasks:
  - include: tasks/main.yml
  - include: tasks/install-init-script.yml

  #handlers:
  # - include: handlers/main.yml
