- name: sickbeard | ensure copy init script exists 
  template: src=root/etc/default/sickbeard.j2 dest=/etc/default/sickbeard owner=root group=root mode=0755

- name: sickbeard | ensure copy init script exists 
  template: src=root/etc/init.d/sickbeard.j2 dest=/etc/init.d/sickbeard owner=root group=root mode=0755

- name: sickbeard | Make sickbeard start on boot 
  command: update-rc.d sickbeard defaults 21

- name: sickbeard | Start/Restart sickbeard
  service: name=sickbeard state=started
